import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const $=s=>document.querySelector(s), state={user:null,cart:JSON.parse(localStorage.getItem("cart")||"[]"),products:[]};
const peso=n=>Number(n||0).toLocaleString("en-PH",{minimumFractionDigits:2});
function saveCart(){localStorage.setItem("cart",JSON.stringify(state.cart));$("#cartCount").textContent=state.cart.reduce((a,x)=>a+x.qty,0)}
async function loadProducts(){let q=supabase.from("products").select("*,profiles(display_name)").eq("is_active",true).order("created_at",{ascending:false});let{data,error}=await q;if(error)return alert(error.message);state.products=data||[];renderProducts()}
function renderProducts(){let term=$("#search").value.toLowerCase(),cat=$("#category").value;$("#products").innerHTML=state.products.filter(p=>(!term||p.title.toLowerCase().includes(term))&&(!cat||p.category===cat)).map(p=>`<article class="product"><img src="${p.image_url||'https://placehold.co/600x700?text=Fashion'}"><div class="info"><div class="meta">${p.category||"Fashion"} • ${p.profiles?.display_name||"Seller"}</div><b>${esc(p.title)}</b><div class="price">₱${peso(p.price)}</div><div class="meta">★ ${Number(p.rating_avg||0).toFixed(1)} (${p.review_count||0})</div><button onclick="addCart('${p.id}')">Add to cart</button></div></article>`).join("")||"<p>No products found.</p>"}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
window.addCart=id=>{let p=state.products.find(x=>x.id===id),x=state.cart.find(x=>x.id===id);x?x.qty++:state.cart.push({id:p.id,title:p.title,price:Number(p.price),qty:1});saveCart();renderCart()}
function renderCart(){$("#cartItems").innerHTML=state.cart.map(x=>`<div class="cart-item"><span>${esc(x.title)} × ${x.qty}</span><b>₱${peso(x.price*x.qty)}</b></div>`).join("")||"<p>Your cart is empty.</p>";$("#cartTotal").textContent=peso(state.cart.reduce((a,x)=>a+x.price*x.qty,0))}
async function session(){let{data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;$("#authBtn").classList.toggle("hidden",!!state.user);$("#logoutBtn").classList.toggle("hidden",!state.user);$("#sellerNav").classList.toggle("hidden",!state.user)}
function modal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
$("#modal").addEventListener("click",e=>{if(e.target===$("#modal")||e.target.closest(".close"))$("#modal").classList.add("hidden")});
$("#authBtn").onclick=()=>modal(`<h2>Welcome</h2><form id="authForm" class="auth-form"><input name="name" placeholder="Display name (registration)" /><input name="gcash" placeholder="GCash number (registration)" /><input required type="email" name="email" placeholder="Email"/><input required type="password" name="password" placeholder="Password (min. 6 chars)"/><button name="mode" value="login">Login</button><button name="mode" value="register">Register</button></form><p class="meta">Registration creates your buyer/seller account. GCash number is stored only for account information; do not use it as a payment credential.</p>`);
document.addEventListener("submit",async e=>{if(e.target.id==="authForm"){e.preventDefault();let f=new FormData(e.target),email=f.get("email"),password=f.get("password"),mode=e.submitter.value;if(mode==="login"){let{error}=await supabase.auth.signInWithPassword({email,password});if(error)return alert(error.message)}else{let{data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:f.get("name")}}});if(error)return alert(error.message);if(data.user){await supabase.from("profiles").upsert({id:data.user.id,display_name:f.get("name"),gcash_number:f.get("gcash")})}alert("Registration successful. Check your email if confirmation is enabled.")}$("#modal").classList.add("hidden");await session();await loadDashboard()}})
$("#logoutBtn").onclick=async()=>{await supabase.auth.signOut();state.user=null;await session();$("#dashContent").innerHTML=""}
async function loadDashboard(tab="sell"){if(!state.user){$("#dashContent").innerHTML="<p>Please log in to access your dashboard.</p>";return}document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));if(tab==="sell"){let{data}=await supabase.from("products").select("*").eq("seller_id",state.user.id).order("created_at",{ascending:false});$("#dashContent").innerHTML=`<div class="dash-card"><h3>Post a product</h3><form id="productForm" class="form-grid"><input name="title" required placeholder="Product name"><select name="category"><option>Women</option><option>Men</option><option>Accessories</option><option>Shoes</option></select><input name="price" required type="number" min="1" step=".01" placeholder="Price (PHP)"><input name="image_url" placeholder="Public image URL"><textarea name="description" placeholder="Description"></textarea><button class="cta">Publish product</button></form><h3>Your products</h3>${(data||[]).map(p=>`<p><b>${esc(p.title)}</b> — ₱${peso(p.price)}</p>`).join("")||"<p>No products yet.</p>"}</div>`}else if(tab==="sales"){let{data,error}=await supabase.from("order_items").select("quantity,unit_price,products(title),orders!inner(status,created_at,seller_id)").eq("orders.seller_id",state.user.id).order("created_at",{foreignTable:"orders",ascending:false});$("#dashContent").innerHTML=`<div class="dash-card"><h3>Sales history</h3>${error?`<p>${esc(error.message)}</p>`:(data||[]).map(x=>`<p>${esc(x.products?.title)} × ${x.quantity} — ₱${peso(x.unit_price*x.quantity)} <span class="meta">${x.orders.status}</span></p>`).join("")||"<p>No sales yet.</p>"}</div>`}else{let{data,error}=await supabase.from("orders").select("*,order_items(quantity,unit_price,products(title))").eq("buyer_id",state.user.id).order("created_at",{ascending:false});$("#dashContent").innerHTML=`<div class="dash-card"><h3>Bought history</h3>${error?`<p>${esc(error.message)}</p>`:(data||[]).map(o=>`<div><b>Order ${o.id.slice(0,8)}</b> — ₱${peso(o.total_amount)} — ${o.status}<br>${o.order_items.map(i=>esc(i.products?.title)+" × "+i.quantity).join(", ")}</div><hr>`).join("")||"<p>No purchases yet.</p>"}</div>`}}
document.addEventListener("click",e=>{let b=e.target.closest("[data-tab]");if(b)loadDashboard(b.dataset.tab)});
document.addEventListener("submit",async e=>{if(e.target.id==="productForm"){e.preventDefault();let f=new FormData(e.target);let{error}=await supabase.from("products").insert({seller_id:state.user.id,title:f.get("title"),category:f.get("category"),price:Number(f.get("price")),image_url:f.get("image_url"),description:f.get("description")});if(error)return alert(error.message);e.target.reset();loadProducts();loadDashboard("sell")}})
$("#search").oninput=renderProducts;$("#category").onchange=renderProducts;
$("#cartBtn").onclick=()=>{$("#cartPanel").classList.remove("hidden");renderCart()};$("#cartPanel .close").onclick=()=>$("#cartPanel").classList.add("hidden");
$("#checkoutBtn").onclick=async()=>{if(!state.user)return alert("Please log in first.");if(!state.cart.length)return;let r=await fetch("/api/create-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:state.cart})});let d=await r.json();if(!r.ok)return alert(d.error||"Checkout failed");location.href=d.checkout_url};
$("#chatToggle").onclick=()=>$("#chatBox").classList.toggle("hidden");$("#chatForm").onsubmit=e=>{e.preventDefault();let i=$("#chatInput"),m=i.value.trim();if(!m)return;$("#chatMessages").innerHTML+=`<p><b>You:</b> ${esc(m)}</p><p><b>Assistant:</b> For live AI, paste your Voiceflow web chat embed in index.html. This local fallback can answer basic shopping questions.</p>`;i.value=""};
saveCart();session();loadProducts();loadDashboard();
